default: &default
  adapter: postgresql
  encoding: unicode
  username: side_quest_user
  password: "<%= ENV['SIDE_QUEST_DATABASE_PASSWORD'] %>"
  host: localhost
  pool: 5

development:
  <<: *default
  database: side_quest_development

test:
  <<: *default
  database: side_quest_test

production:
  <<: *default
  database: side_quest_production
  username: side_quest_prod
  password: "<%= ENV['SIDE_QUEST_DATABASE_PASSWORD'] %>"
